config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :user_list
  resources :post

   root 'post#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_list.rb
class UserList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form_for_post.html.erb
<% if user_signed_in? %>
	<%= form_for @post do |f| %>
		<!-- this is where the file field for avatar picture goes. -->
		<%= f.label :title %>
		<%= f.text_area :title %>
		<br />
		<%= f.label :author %>
		<%= f.text_area :author %>
		<%= f.hidden_field :user_id, value: params[:user_id] %>
		<br />
		<%= f.submit %>
 <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your Bucket List Item</h1>
	<%= render(partial:'form_for_post') %>

app/views/posts/index.html.erb
<h1>Bucket Lists</h1>
	<% @posts.each do |post| %>
<!-- these go in the cards themselves -->
		<h3><%= post.title %></h3>
		<h4><%= post.author %></h4>
<!-- not sure if we end the card thing here -->
	<%= link_to 'Show Posts', post_path(post) %>
	<% if user_signed_in? %>
		<%= link_to 'Edit Post', edit_post_path(post) %>
		<%= link_to 'Delete Post', post_path(post), method: :delete, data: {confirm: "Do you really want to delete this Post?"} %>
	<% end %>
<!-- or here -->
<% end %>
<%= link_to 'New User', new_user_path, %>
		

app/views/posts/new.html.erb
<h1>Create a New thing to do before you kick the bucket</h1>
<%= render(partial:'form_for_post') %>

app/views/posts/show.html.erb
<h1>Something to do before you kick the Bucket</h1>
<!-- this is where the picture goes, avatar thing -->
	<h2><%= @post.title %></h2>
	<h3><%= @post.author %></h3>
<%= link_to 'Back' post_index_path %>

app/views/user_lists/index.html.erb
<h1>UserLists#index</h1>
<p>Find me in app/views/user_lists/index.html.erb</p>

app/views/user_lists/new.html.erb
<h1>UserLists#new</h1>
<p>Find me in app/views/user_lists/new.html.erb</p>

app/views/user_lists/show.html.erb
<h1>UserLists#show</h1>
<p>Find me in app/views/user_lists/show.html.erb</p>

app/views/users/_form_for_user.html.erb
<%= form_for.each do |f| %>
	<%= f.label :name %>
	<%= f.text_area :name %>
	<br />
	<%= f.label :email %>
	<%= f.text_area :email %>
	<br />
	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Create a New User</h1>
<br />
<%= render(partial:'form_for_user') %>

app/views/users/index.html.erb
<!-- nothing needed in here -->

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>